"""Generate ATT&CK Navigator JSON layers and HTML reports from CoverageResults.

Produces self-contained, dependency-free output files suitable for sharing
with stakeholders or archiving alongside detection engineering artifacts.
"""

from __future__ import annotations

import html
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from chef_pantry.models.evidence import CoverageResult, EvidenceChain


def _esc(value: object) -> str:
    """Escape a value for safe inclusion in HTML output."""
    return html.escape(str(value))


# ---------------------------------------------------------------------------
# Colour constants
# ---------------------------------------------------------------------------

_GREEN = "#2ecc71"
_RED = "#e74c3c"
_CYAN = "#00d2ff"
_DARK_BG = "#1a1a2e"
_CARD_BG = "#16213e"
_TEXT = "#e0e0e0"


# ---------------------------------------------------------------------------
# ATT&CK Navigator JSON layer
# ---------------------------------------------------------------------------


def generate_navigator_json(result: CoverageResult) -> dict[str, Any]:
    """Create an ATT&CK Navigator layer dict from a ``CoverageResult``.

    The returned dict conforms to the Navigator layer JSON schema and can be
    imported directly into https://mitre-attack.github.io/attack-navigator/.
    """
    techniques: list[dict[str, Any]] = []
    for chain in result.evidence_chains:
        detected = chain.is_detected
        comment_parts: list[str] = [f"Status: {chain.status}"]
        if chain.detections:
            matched_rules = ", ".join(d.rule_name for d in chain.detections)
            alert_ids = ", ".join(d.alert_id for d in chain.detections)
            comment_parts.append(f"Rules: {matched_rules}")
            comment_parts.append(f"Alerts: {alert_ids}")
        if chain.notes:
            comment_parts.append(f"Notes: {chain.notes}")

        techniques.append(
            {
                "techniqueID": chain.technique.id,
                "color": _GREEN if detected else _RED,
                "score": 100 if detected else 0,
                "comment": " | ".join(comment_parts),
                "enabled": True,
            }
        )

    return {
        "name": f"PurpleChef Coverage: {result.recipe_name}",
        "versions": {
            "attack": "15",
            "navigator": "5.1.0",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": (
            f"Auto-generated by PurpleChef | Run: {result.run_id} | "
            f"{result.detected_count}/{result.total_count} techniques detected"
        ),
        "gradient": {
            "colors": [_RED, _GREEN],
            "minValue": 0,
            "maxValue": 100,
        },
        "techniques": techniques,
    }


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------


def _status_icon(chain: EvidenceChain) -> str:
    if chain.is_detected:
        return "&#10004;"  # checkmark
    return "&#10008;"  # cross


def _pct_bar_color(pct: float) -> str:
    if pct >= 75:
        return _GREEN
    if pct >= 40:
        return "#f39c12"  # amber
    return _RED


def generate_html_report(result: CoverageResult) -> str:
    """Return a self-contained HTML string for a ``CoverageResult``.

    Uses inline CSS only — no external stylesheets or JavaScript dependencies.
    """
    pct = result.coverage_percentage
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    # -- Coverage cards --
    cards: list[str] = []
    for chain in result.evidence_chains:
        detected = chain.is_detected
        border = _GREEN if detected else _RED
        icon = _status_icon(chain)
        icon_color = _GREEN if detected else _RED
        alert_ids = (
            ", ".join(_esc(d.alert_id) for d in chain.detections) if chain.detections else "---"
        )
        cards.append(
            f'<div class="card" style="border-left:4px solid {border};">'
            f'  <div class="card-id">{_esc(chain.technique.id)}</div>'
            f'  <div class="card-name">{_esc(chain.technique.name)}</div>'
            f'  <div class="card-icon" style="color:{icon_color};">{icon}</div>'
            f'  <div class="card-detail">Detections: {chain.detection_count}</div>'
            f'  <div class="card-detail">Alerts: {alert_ids}</div>'
            f"</div>"
        )

    # -- Evidence table rows --
    rows: list[str] = []
    for chain in result.evidence_chains:
        matched_rules = (
            ", ".join(_esc(d.rule_name) for d in chain.detections) if chain.detections else "---"
        )
        alert_ids = (
            ", ".join(_esc(d.alert_id) for d in chain.detections) if chain.detections else "---"
        )
        status_color = _GREEN if chain.is_detected else _RED
        rows.append(
            f"<tr>"
            f"  <td>{_esc(chain.technique.id)}</td>"
            f"  <td>{_esc(chain.technique.name)}</td>"
            f"  <td>{_esc(chain.emulation_id)}</td>"
            f"  <td>{chain.execution_start.strftime('%H:%M:%S')} &mdash; "
            f"{chain.execution_end.strftime('%H:%M:%S')}</td>"
            f'  <td style="color:{status_color};font-weight:700;">{_esc(chain.status.upper())}</td>'
            f"  <td>{matched_rules}</td>"
            f"  <td>{alert_ids}</td>"
            f"</tr>"
        )

    bar_color = _pct_bar_color(pct)

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PurpleChef Coverage Report — {_esc(result.recipe_name)}</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ background:{_DARK_BG}; color:{_TEXT}; font-family:'Segoe UI',system-ui,sans-serif; padding:2rem; }}
  .header {{ text-align:center; margin-bottom:2rem; }}
  .header h1 {{ color:{_CYAN}; font-size:2rem; margin-bottom:.3rem; }}
  .header .sub {{ opacity:.7; font-size:.9rem; }}
  .summary {{ display:flex; justify-content:center; gap:2rem; margin-bottom:2rem; flex-wrap:wrap; }}
  .summary-box {{ background:{_CARD_BG}; border-radius:8px; padding:1.2rem 2rem; text-align:center; min-width:160px; }}
  .summary-box .num {{ font-size:2rem; font-weight:700; color:{_CYAN}; }}
  .summary-box .label {{ font-size:.85rem; opacity:.7; margin-top:.2rem; }}
  .bar-wrap {{ max-width:600px; margin:0 auto 2rem; background:#0f3460; border-radius:6px; height:28px; overflow:hidden; }}
  .bar-fill {{ height:100%; border-radius:6px; transition:width .3s; display:flex; align-items:center; justify-content:center; font-weight:700; font-size:.85rem; color:#fff; }}
  .cards {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(240px,1fr)); gap:1rem; margin-bottom:2.5rem; }}
  .card {{ background:{_CARD_BG}; border-radius:8px; padding:1rem 1.2rem; }}
  .card-id {{ font-weight:700; color:{_CYAN}; font-size:1.05rem; }}
  .card-name {{ font-size:.85rem; opacity:.8; margin-bottom:.5rem; }}
  .card-icon {{ font-size:1.6rem; margin:.3rem 0; }}
  .card-detail {{ font-size:.8rem; opacity:.65; }}
  table {{ width:100%; border-collapse:collapse; margin-bottom:2rem; }}
  th {{ background:#0f3460; color:{_CYAN}; padding:.7rem .6rem; text-align:left; font-size:.85rem; }}
  td {{ padding:.6rem; border-bottom:1px solid #1e3a5f; font-size:.83rem; }}
  tr:hover td {{ background:rgba(0,210,255,0.04); }}
  .footer {{ text-align:center; opacity:.4; font-size:.8rem; padding-top:2rem; border-top:1px solid #1e3a5f; }}
</style>
</head>
<body>

<div class="header">
  <h1>PurpleChef Coverage Report</h1>
  <div class="sub">{_esc(result.recipe_name)} &mdash; {now} &mdash; Run: {_esc(result.run_id)}</div>
</div>

<div class="summary">
  <div class="summary-box"><div class="num">{result.detected_count}/{result.total_count}</div><div class="label">Techniques Detected</div></div>
  <div class="summary-box"><div class="num">{pct:.1f}%</div><div class="label">Coverage</div></div>
  <div class="summary-box"><div class="num">{result.missed_count}</div><div class="label">Missed</div></div>
</div>

<div class="bar-wrap">
  <div class="bar-fill" style="width:{pct:.1f}%;background:{bar_color};">{pct:.1f}%</div>
</div>

<h2 style="color:{_CYAN};margin-bottom:1rem;">Coverage Cards</h2>
<div class="cards">
{chr(10).join(cards)}
</div>

<h2 style="color:{_CYAN};margin-bottom:1rem;">Evidence Details</h2>
<table>
<thead>
<tr><th>Technique</th><th>Name</th><th>Emulation ID</th><th>Time Window</th><th>Status</th><th>Matched Rules</th><th>Alert IDs</th></tr>
</thead>
<tbody>
{chr(10).join(rows)}
</tbody>
</table>

<div class="footer">Generated by PurpleChef</div>

</body>
</html>"""
    return html


# ---------------------------------------------------------------------------
# Save helper
# ---------------------------------------------------------------------------


def save_report(
    result: CoverageResult,
    output_dir: Path,
    formats: list[str],
) -> list[Path]:
    """Write reports in the requested formats and return the list of file paths.

    Supported format strings: ``"json"``, ``"html"``, ``"navigator"``.

    * ``json`` — full ``CoverageResult`` serialised as JSON.
    * ``html`` — self-contained HTML report.
    * ``navigator`` — ATT&CK Navigator layer JSON.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = f"purplechef_{result.run_id}"
    written: list[Path] = []

    for fmt in formats:
        fmt_lower = fmt.strip().lower()

        if fmt_lower == "json":
            path = output_dir / f"{stem}_coverage.json"
            path.write_text(
                result.model_dump_json(indent=2),
                encoding="utf-8",
            )
            written.append(path)

        elif fmt_lower == "navigator":
            path = output_dir / f"{stem}_navigator.json"
            layer = generate_navigator_json(result)
            path.write_text(
                json.dumps(layer, indent=2, default=str),
                encoding="utf-8",
            )
            written.append(path)

        elif fmt_lower == "html":
            path = output_dir / f"{stem}_report.html"
            path.write_text(generate_html_report(result), encoding="utf-8")
            written.append(path)

        else:
            raise ValueError(f"Unknown report format '{fmt}'. Supported: json, html, navigator.")

    return written
